import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";
import useOnScreen from "../hooks/useOnScreen";
import { useRef } from "react";
import bumpLogo from "../images/bump-logo.svg";

export default function Home() {
  const workRef = useRef();
  const isWorkVisible = useOnScreen(workRef, "-200px");
  const contactRef = useRef();
  const isContactVisible = useOnScreen(contactRef, "-200px");
  return (
    <Layout>
      <div>
        <Head>
          <title>Kerk Zhan</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/blob.svg" />
        </Head>

        {/* <div className="kp-line"></div> */}
        <section className="kp-layout-section kp-stack-128">
          <div className="kp-layout-hero">
            <p className="kp-hero-description">
              <strong> Boon Kerk Zhan </strong>(b. 1997, Malaysia) <br />
              is an <strong>independent web developer</strong> who loves
              exploring technology and its ever evolving state. <br />
              <br />I love creating websites that provide experiences that leave
              a lasting memory on people. I am also exploring in creating{" "}
              <strong>design systems</strong> for a more flexible web. I
              documented the process of how I made this website with design
              systems <a>here</a>.
            </p>
          </div>
          {/* 
          <div className="kp-scroll kp-layout-scroll-line">
            <p>scroll</p>
            <div></div>
          </div> */}
        </section>

        <section className="kp-stack-128">
          <div className="kp-layout-section">
            <div
              ref={workRef}
              className={`hidden-text ${
                isWorkVisible && `fade-in-text`
              } kp-stack-64`}
            >
              <h1> Things I created.</h1>
            </div>
            <div>
              <div className="kp-layout-two-column">
                <Image src={bumpLogo} alt="Bump Bouldering Logo" height={200} />
                <div>
                  <h2>BUMP Bouldering</h2>
                  <p>
                    Esse ipsum elit reprehenderit ut irure. Pariatur duis sint
                    nisi nisi non esse enim cillum pariatur eiusmod. Cillum non
                    duis cillum veniam tempor cupidatat mollit occaecat veniam
                    excepteur mollit dolor velit aliqua.
                  </p>
                </div>
              </div>
              <div className="kp-layout-two-column">
                <Image src={bumpLogo} alt="Bump Bouldering Logo" height={200} />
                <div>
                  <h2>BUMP Bouldering</h2>
                  <p>
                    Esse ipsum elit reprehenderit ut irure. Pariatur duis sint
                    nisi nisi non esse enim cillum pariatur eiusmod. Cillum non
                    duis cillum veniam tempor cupidatat mollit occaecat veniam
                    excepteur mollit dolor velit aliqua.
                  </p>
                </div>
              </div>{" "}
              <div className="kp-layout-two-column">
                <Image src={bumpLogo} alt="Bump Bouldering Logo" height={200} />
                <div>
                  <h2>BUMP Bouldering</h2>
                  <p>
                    Esse ipsum elit reprehenderit ut irure. Pariatur duis sint
                    nisi nisi non esse enim cillum pariatur eiusmod. Cillum non
                    duis cillum veniam tempor cupidatat mollit occaecat veniam
                    excepteur mollit dolor velit aliqua.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <div className="kp-line kp-stack-128"></div>
        <section className="kp-layout-section">
          <div
            ref={contactRef}
            className={`hidden-text ${isContactVisible && `fade-in-text`}`}
          >
            <h1>Hit me up!</h1>
          </div>
        </section>
      </div>
    </Layout>
  );
}
