import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kerk Zhan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="kp-layout-default">
        <h1>Korkfolio</h1>

        <p>He is very cool! </p>

        <div>
          <a href="https://nextjs.org/docs">
            <h2>He climbs</h2>
            <p>He can climb 7 dot</p>
          </a>

          <a href="https://nextjs.org/learn">
            <h2>He games</h2>
            <p>He is D2 in Valorant</p>
          </a>
          <a href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>He has 3 cats</h2>
            <p>Their name are Oliver, Genji and Finn</p>
          </a>
          <a href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>He is good boyfriend</h2>
            <p>He is good boyfriend to Gillian except being a plate</p>
          </a>
        </div>
      </main>

      <footer className="kp-layout-footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
