import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";

import bumpLogo from "../images/bump-logo.svg";
import unitarLogo from "../images/unitar-logo.svg";
import lvlupLogo from "../images/lvlup-logo.svg";
import Fade from "react-reveal/Fade";

export default function Home() {
  return (
    <Layout>
      <div>
        <Head>
          <title>Work | Kerk Zhan </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/blob.svg" />
        </Head>

        {/* <div className="kp-line"></div> */}

        <section className="kp-stack-128">
          <div className="kp-layout-section ">
            <Fade>
              <h1 className="kp-stack-64"> Things I worked on.</h1>
            </Fade>
            <div>
              <Fade bottom>
                <div className="kp-layout-two-column">
                  <div className="kp-img-container-fluid">
                    <Image
                      src={bumpLogo}
                      alt="BUMP Bouldering Logo"
                      layout="fill"
                      objectFit="contain"
                    />
                  </div>
                  <div>
                    <h2>BUMP Bouldering Website</h2>
                    <h3 className="kp-text-subdued">asdasd</h3>
                    <p>
                      Esse ipsum elit reprehenderit ut irure. Pariatur duis sint
                      nisi nisi non esse enim cillum pariatur eiusmod. Cillum
                      non duis cillum veniam tempor cupidatat mollit occaecat
                      veniam excepteur mollit dolor velit aliqua.
                    </p>
                  </div>
                </div>
              </Fade>
              <Fade bottom>
                <div className="kp-layout-two-column">
                  <div className="kp-img-container-fluid">
                    <Image
                      src={unitarLogo}
                      alt="UNITAR Logo"
                      layout="fill"
                      objectFit="contain"
                    />
                  </div>
                  <div>
                    <h2>Hit the Score Quiz App</h2>
                    <p>
                      Esse ipsum elit reprehenderit ut irure. Pariatur duis sint
                      nisi nisi non esse enim cillum pariatur eiusmod. Cillum
                      non duis cillum veniam tempor cupidatat mollit occaecat
                      veniam excepteur mollit dolor velit aliqua.
                    </p>
                  </div>
                </div>
              </Fade>

              <Fade bottom>
                <div className="kp-layout-two-column">
                  <div className="kp-img-container-fluid">
                    <Image
                      src={lvlupLogo}
                      alt="BUMP Bouldering Logo"
                      layout="fill"
                      objectFit="contain"
                    />
                  </div>
                  <div>
                    <h2>BUMP Bouldering</h2>
                    <p>
                      Esse ipsum elit reprehenderit ut irure. Pariatur duis sint
                      nisi nisi non esse enim cillum pariatur eiusmod. Cillum
                      non duis cillum veniam tempor cupidatat mollit occaecat
                      veniam excepteur mollit dolor velit aliqua.
                    </p>
                  </div>
                </div>
              </Fade>
            </div>
          </div>
        </section>
      </div>
    </Layout>
  );
}
